language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run check
  - npm run cover
  - npm run docs

# Upload test coverage to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Deploy documentation to Github Pages
# See https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master
