window.esdocSearchIndex = [
  [
    "stencila-js/src/jsglobals.js~jsglobals",
    "variable/index.html#static-variable-JSGLOBALS",
    "<span>JSGLOBALS</span> <span class=\"search-result-import-path\">stencila-js/src/JSGLOBALS.js</span>",
    "variable"
  ],
  [
    "stencila-js/src/javascriptcontext.js~javascriptcontext",
    "class/src/JavascriptContext.js~JavascriptContext.html",
    "<span>JavascriptContext</span> <span class=\"search-result-import-path\">stencila-js/src/JavascriptContext.js</span>",
    "class"
  ],
  [
    "stencila-js/src/types.js~childrentypes",
    "variable/index.html#static-variable-childrenTypes",
    "<span>childrenTypes</span> <span class=\"search-result-import-path\">stencila-js/src/types.js</span>",
    "variable"
  ],
  [
    "stencila-js/src/types.js~coercearray",
    "function/index.html#static-function-coerceArray",
    "<span>coerceArray</span> <span class=\"search-result-import-path\">stencila-js/src/types.js</span>",
    "function"
  ],
  [
    "stencila-js/src/types.js~coercedarraytype",
    "function/index.html#static-function-coercedArrayType",
    "<span>coercedArrayType</span> <span class=\"search-result-import-path\">stencila-js/src/types.js</span>",
    "function"
  ],
  [
    "stencila-js/src/collectargs.js~collectargs",
    "function/index.html#static-function-collectArgs",
    "<span>collectArgs</span> <span class=\"search-result-import-path\">stencila-js/src/collectArgs.js</span>",
    "function"
  ],
  [
    "stencila-js/src/compilefunction.js~compilefunction",
    "function/index.html#static-function-compileFunction",
    "<span>compileFunction</span> <span class=\"search-result-import-path\">stencila-js/src/compileFunction.js</span>",
    "function"
  ],
  [
    "stencila-js/src/compilejavascript.js~compilejavascript",
    "function/index.html#static-function-compileJavascript",
    "<span>compileJavascript</span> <span class=\"search-result-import-path\">stencila-js/src/compileJavascript.js</span>",
    "function"
  ],
  [
    "stencila-js/src/types.js~descendanttypes",
    "variable/index.html#static-variable-descendantTypes",
    "<span>descendantTypes</span> <span class=\"search-result-import-path\">stencila-js/src/types.js</span>",
    "variable"
  ],
  [
    "stencila-js/src/packerror.js~extractdetailsfromerror",
    "function/index.html#static-function-extractDetailsFromError",
    "<span>extractDetailsFromError</span> <span class=\"search-result-import-path\">stencila-js/src/packError.js</span>",
    "function"
  ],
  [
    "stencila-js/src/extractfunctionspecfromdoc.js~extractfunctionspecfromdoc",
    "function/index.html#static-function-extractFunctionSpecFromDoc",
    "<span>extractFunctionSpecFromDoc</span> <span class=\"search-result-import-path\">stencila-js/src/extractFunctionSpecFromDoc.js</span>",
    "function"
  ],
  [
    "stencila-js/src/findglobals.js~findglobals",
    "function/index.html#static-function-findGlobals",
    "<span>findGlobals</span> <span class=\"search-result-import-path\">stencila-js/src/findGlobals.js</span>",
    "function"
  ],
  [
    "stencila-js/src/types.js~pack",
    "function/index.html#static-function-pack",
    "<span>pack</span> <span class=\"search-result-import-path\">stencila-js/src/types.js</span>",
    "function"
  ],
  [
    "stencila-js/src/types.js~parenttypes",
    "variable/index.html#static-variable-parentTypes",
    "<span>parentTypes</span> <span class=\"search-result-import-path\">stencila-js/src/types.js</span>",
    "variable"
  ],
  [
    "stencila-js/src/parsevalue.js~parsevalue",
    "function/index.html#static-function-parseValue",
    "<span>parseValue</span> <span class=\"search-result-import-path\">stencila-js/src/parseValue.js</span>",
    "function"
  ],
  [
    "stencila-js/src/types.js~type",
    "function/index.html#static-function-type",
    "<span>type</span> <span class=\"search-result-import-path\">stencila-js/src/types.js</span>",
    "function"
  ],
  [
    "stencila-js/src/types.js~unpack",
    "function/index.html#static-function-unpack",
    "<span>unpack</span> <span class=\"search-result-import-path\">stencila-js/src/types.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/jsglobals.js",
    "file/src/JSGLOBALS.js.html",
    "src/JSGLOBALS.js",
    "file"
  ],
  [
    "src/javascriptcontext.js",
    "file/src/JavascriptContext.js.html",
    "src/JavascriptContext.js",
    "file"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#_collectinputs",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-method-_collectInputs",
    "src/JavascriptContext.js~JavascriptContext#_collectInputs",
    "method"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#_host",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-member-_host",
    "src/JavascriptContext.js~JavascriptContext#_host",
    "member"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#_id",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-member-_id",
    "src/JavascriptContext.js~JavascriptContext#_id",
    "member"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#_libraries",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-member-_libraries",
    "src/JavascriptContext.js~JavascriptContext#_libraries",
    "member"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#_values",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-member-_values",
    "src/JavascriptContext.js~JavascriptContext#_values",
    "member"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#compile",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-method-compile",
    "src/JavascriptContext.js~JavascriptContext#compile",
    "method"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#constructor",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-constructor-constructor",
    "src/JavascriptContext.js~JavascriptContext#constructor",
    "method"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#evaluatecall",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-method-evaluateCall",
    "src/JavascriptContext.js~JavascriptContext#evaluateCall",
    "method"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#execute",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-method-execute",
    "src/JavascriptContext.js~JavascriptContext#execute",
    "method"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#id",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-get-id",
    "src/JavascriptContext.js~JavascriptContext#id",
    "member"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#importlibrary",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-method-importLibrary",
    "src/JavascriptContext.js~JavascriptContext#importLibrary",
    "method"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#pack",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-method-pack",
    "src/JavascriptContext.js~JavascriptContext#pack",
    "method"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#resolve",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-method-resolve",
    "src/JavascriptContext.js~JavascriptContext#resolve",
    "method"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#resolvefunction",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-method-resolveFunction",
    "src/JavascriptContext.js~JavascriptContext#resolveFunction",
    "method"
  ],
  [
    "src/javascriptcontext.js~javascriptcontext#unpack",
    "class/src/JavascriptContext.js~JavascriptContext.html#instance-method-unpack",
    "src/JavascriptContext.js~JavascriptContext#unpack",
    "method"
  ],
  [
    "src/collectargs.js",
    "file/src/collectArgs.js.html",
    "src/collectArgs.js",
    "file"
  ],
  [
    "src/compilefunction.js",
    "file/src/compileFunction.js.html",
    "src/compileFunction.js",
    "file"
  ],
  [
    "src/compilejavascript.js",
    "file/src/compileJavascript.js.html",
    "src/compileJavascript.js",
    "file"
  ],
  [
    "src/extractfunctionspecfromdoc.js",
    "file/src/extractFunctionSpecFromDoc.js.html",
    "src/extractFunctionSpecFromDoc.js",
    "file"
  ],
  [
    "src/findglobals.js",
    "file/src/findGlobals.js.html",
    "src/findGlobals.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/packerror.js",
    "file/src/packError.js.html",
    "src/packError.js",
    "file"
  ],
  [
    "src/parsevalue.js",
    "file/src/parseValue.js.html",
    "src/parseValue.js",
    "file"
  ],
  [
    "src/types.js",
    "file/src/types.js.html",
    "src/types.js",
    "file"
  ]
]